spring.application.name=devpulse-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/devpulse}
spring.datasource.username=${DB_USERNAME:devpulse_app}
spring.datasource.password=${DB_PASSWORD}

server.port=${PORT:8080}
spring.flyway.url=${DB_MIGRATION_URL:${spring.datasource.url}}
spring.flyway.user=${DB_MIGRATION_USERNAME:devpulse_migrator}
spring.flyway.password=${DB_MIGRATION_PASSWORD}
spring.flyway.default-schema=devpulse
spring.flyway.schemas=devpulse
spring.flyway.create-schemas=false
spring.flyway.clean-disabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never
